language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

script:
  - python setup.py -q nosetests

notifications:
  email: false
